# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ac_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# -*- coding: utf-8 -*-
import os
import struct
import time

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# SPDX-License-Identifier: GPL-2.0-or-later
from PyQt5 import QtCore
from PyQt5.QtCore import pyqtSignal, QObject, QSize,Qt,QCoreApplication
from PyQt5.QtGui import QColor, QFont, QPalette
from PyQt5.QtWidgets import QWidget, QPushButton, QHBoxLayout, QVBoxLayout, QSizePolicy, QGridLayout, QLabel, QSlider, \
    QComboBox, QColorDialog, QCheckBox, QLineEdit, QButtonGroup, QRadioButton, QFileDialog, QMessageBox
from PyQt5.QtGui import QColor,QImage,QPixmap
from basic_editor import BasicEditor
from Send_alarm import SendAlarm
from PIL import Image
import cv2
tr = QCoreApplication.translate


class BasicHandler(QObject):
    update = pyqtSignal()

    def __init__(self, container):
        super().__init__()
        self.device = self.keyboard = None
        self.widgets = []

    def set_device(self, device):
        self.device = device
        if self.valid():
            # self.keyboard = self.device.keyboard
            self.show()
        else:
            self.hide()

    def show(self):
        for w in self.widgets:
            w.show()

    def hide(self):
        for w in self.widgets:
            w.hide()

    def block_signals(self):
        for w in self.widgets:
            w.blockSignals(True)

    def unblock_signals(self):
        for w in self.widgets:
            w.blockSignals(False)

    # def update_from_keyboard(self):
    #     raise NotImplementedError
    #
    # def valid(self):
    #     raise NotImplementedError

class NetConfigSetHandler(BasicHandler):

    def __init__(self, container):
        super().__init__(container)

    def valid(self):
        return 1
        # return isinstance(self.device, VialKeyboard) #and self.device.keyboard.lighting_qmk_rgblight

    def send_cmd(self,strmsg):
        byte_array = strmsg.encode()
        print(type(byte_array),len(byte_array))  # <class 'bytes'>
        print(byte_array)  #
        #hex_data = byte_array.hex()
        return self.device.keyboard.set_custom_setting(byte_array)


    def send_cmd_str(self,strmsg):
        byte_array = strmsg.encode()
        print(type(byte_array),len(byte_array))  # <class 'bytes'>
        print(byte_array)  #
        try:
            return self.device.keyboard.set_custom_setting(byte_array)
        except:
            return None
    def send_cmd_hex(self,byte_array):
        #bytes_array是bytes,入参要转换为bytes传入进来
        ret =self.device.keyboard.set_custom_setting(byte_array)
        return ret

    def recv_cmd_hex(self):
        ret = self.device.keyboard.recv_custom_setting()
        return ret


class router_config(BasicEditor):
    def __init__(self):
        super().__init__()
        self.data = dict()
        self.mode = 1

        w = QWidget()
        w.setSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        self.container = QVBoxLayout()

        w.setLayout(self.container)
        self.addWidget(w)
        self.setupUi(w,self.container)

        self.handlers = [NetConfigSetHandler(self.container)]

    def setupUi(self,Form,container):

        self.horizontalLayout_7 = QHBoxLayout()
        self.label_8 = QLabel("标签名称")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.textEdit = QLineEdit()
        self.horizontalLayout_7.addWidget(self.textEdit)
        self.textEdit.textChanged.connect(self.handle_paramver_textedit_changed)
        self.label_9 = QLabel("单位:us")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        container.addLayout(self.horizontalLayout_7)

    def handle_paramver_textedit_changed(self):
        if self.textEdit.hasFocus():
            print("LineEdit has focus")
        else:
            print("LineEdit lost focus")
        if(self.textEdit.text().isdigit()):
            self.param_ver=int(self.textEdit.text())
        print(f"输入的字符串是：{self.param_ver}")

 # layout 移除所有控件
    def remove_all_controls(self,layout):
        while layout.count():
            child = layout.takeAt(0)
            if child is not None:
                if child.widget() is not None:
                    child.widget().deleteLater()
                elif child.layout() is not None:
                    self.clear_layout(child.layout())

    def clear_layout(self,layout):
        while layout is not None and layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()
            else:
                self.clear_layout(item.layout())




    def valid(self):
        # return isinstance(self.device, VialKeyboard)
        return 1

    def rebuild(self, device):
        super().rebuild(device)

        for h in self.handlers:
            h.set_device(device)

        if not self.valid():
            return
        # if len(device.kmapcustom):
        #     print(device.kmapcustom)

